version: '3'

networks:
  metrics:
    driver: bridge
  
services:
  k6:
    container_name: k6
    image: grafana/k6
    networks:
      - metrics
    ports:
      - "6565:6565"
    environment:
      # - K6_OUT=influxdb=http://influxdb:8086/k6
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      
    volumes:
      - ./scripts:/scripts
    

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - metrics
    ports:
      - 3000:3000
    # for influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
      - ./etc/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./etc/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    # for prometheus
    

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - 8086:8086
    environment:
      - INFLUX_DB=k6
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - metrics
