global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'k6'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:6565']

  